<?php if ( ! defined('OMNIVERSE_THEME_DIR')) exit('No direct script access allowed');

/**
 * ------------------------------------------------------------------------------------------------
 * Default options array
 * ------------------------------------------------------------------------------------------------
 */

return apply_filters( 'omniverse_get_base_options', array(
	'main_layout' => 'full-width',
	'page-title-size' => 'small',
	'sidebar_width' => 3,
	'blog_sidebar_width' => 3,
	'footer-layout' => 13,
	'disable_footer' => true,
	'disable_copyrights' => true,
	'copyrights-layout' => 'centered',
	'copyrights' => 'Based on <a href="http://omniverse.zynxsol.com"><strong>OmniVerse</strong></a> theme<i class="fa fa-copyright"></i> ' . date( 'Y' ) . ' <a href="https://themeforest.net/item/omniverse-woocommerce-wordpress-theme/20264492"><strong>WooCommerce Themes</strong></a>.',
	'blog_excerpt' => 'excerpt',
	'page-title-design' => 'centered',
	'page-title-color' => 'light',
	'custom_css' => '.page-title-default { background-color: #0a0a0a; }',
	'page_comments' => true,
	'shop_view' => 'grid',
	'products_columns' => 3,
	'products_columns_mobile' => 2,
	'thums_position' => 'bottom',
	'product_short_description' => true,
	'product_tabs_layout' => 'tabs',
	'related_products' => true,
	'hover_image' => true,
	'products_hover' => 'base',
	'blog_design' => 'default',
	'primary-color' => '#83B735',
	'secondary-color' => '#FBBC34',
) );

$omniverse_core_translations = array(
	esc_html__( 'You are now logged in as <strong>%s</strong>', 'omniverse' ),
	esc_html__( 'Slider', 'omniverse' ),
	esc_html__( 'Slide', 'omniverse' ),
	esc_html__( 'Slides', 'omniverse' ),
	esc_html__( 'Parent Item:', 'omniverse' ),
	esc_html__( 'All Items', 'omniverse' ),
	esc_html__( 'View Item', 'omniverse' ),
	esc_html__( 'Add New Item', 'omniverse' ),
	esc_html__( 'Add New', 'omniverse' ),
	esc_html__( 'Edit Item', 'omniverse' ),
	esc_html__( 'Update Item', 'omniverse' ),
	esc_html__( 'Search Item', 'omniverse' ),
	esc_html__( 'Not found', 'omniverse' ),
	esc_html__( 'Not found in Trash', 'omniverse' ),
	esc_html__( 'Sliders', 'omniverse' ),
	esc_html__( 'Slider', 'omniverse' ),
	esc_html__( 'Search Sliders', 'omniverse' ),
	esc_html__( 'Popular Sliders', 'omniverse' ),
	esc_html__( 'All Sliders', 'omniverse' ),
	esc_html__( 'Parent Slider', 'omniverse' ),
	esc_html__( 'Parent Slider', 'omniverse' ),
	esc_html__( 'Edit Slider', 'omniverse' ),
	esc_html__( 'Update Slider', 'omniverse' ),
	esc_html__( 'Add New Slider', 'omniverse' ),
	esc_html__( 'New Slide', 'omniverse' ),
	esc_html__( 'Add or remove Sliders', 'omniverse' ),
	esc_html__( 'Choose from most used sliders', 'omniverse' ),
	esc_html__( 'Slider', 'omniverse' ),
	esc_html__( 'Size guides', 'omniverse' ),
	esc_html__( 'Size guide', 'omniverse' ),
	esc_html__( 'Size guides', 'omniverse' ),
	esc_html__( 'Add new', 'omniverse' ),
	esc_html__( 'Add new size guide', 'omniverse' ),
	esc_html__( 'New size guide', 'omniverse' ),
	esc_html__( 'Edit size guide', 'omniverse' ),
	esc_html__( 'View size guide', 'omniverse' ),
	esc_html__( 'All size guides', 'omniverse' ),
	esc_html__( 'Search size guides', 'omniverse' ),
	esc_html__( 'No size guides found.', 'omniverse' ),
	esc_html__( 'No size guides found in trash.', 'omniverse' ),
	esc_html__( 'omniverse_size_guide', 'omniverse' ),
	esc_html__( 'Size guide to place in your products', 'omniverse' ),
	esc_html__( 'HTML Blocks', 'omniverse' ),
	esc_html__( 'HTML Block', 'omniverse' ),
	esc_html__( 'HTML Blocks', 'omniverse' ),
	esc_html__( 'CMS Blocks for custom HTML to place in your pages', 'omniverse' ),
	esc_html__( 'Title', 'omniverse' ),
	esc_html__( 'Shortcode', 'omniverse' ),	   
	esc_html__( 'Sidebar', 'omniverse' ),
	esc_html__( 'Sidebars', 'omniverse' ),
	esc_html__( 'You can create additional custom sidebar and use them in Visual Composer', 'omniverse' ),
	esc_html__( 'Portfolio', 'omniverse' ),
	esc_html__( 'Project', 'omniverse' ),
	esc_html__( 'Projects', 'omniverse' ),
	esc_html__( 'Project Categories', 'omniverse' ),
	esc_html__( 'Project Category', 'omniverse' ),
	esc_html__( 'Search Categories', 'omniverse' ),
	esc_html__( 'Popular Project Categories', 'omniverse' ),
	esc_html__( 'All Project Categories', 'omniverse' ),
	esc_html__( 'Parent Category', 'omniverse' ),
	esc_html__( 'Parent Category', 'omniverse' ),
	esc_html__( 'Edit Category', 'omniverse' ),
	esc_html__( 'Update Category', 'omniverse' ),
	esc_html__( 'Add New Category', 'omniverse' ),
	esc_html__( 'New Category', 'omniverse' ),
	esc_html__( 'Add or remove Categories', 'omniverse' ),
	esc_html__( 'Choose from most used text-domain', 'omniverse' ),
	esc_html__( 'Category', 'omniverse' ),
	esc_html__( 'Categories', 'omniverse' ),
	esc_html__( 'Product 360 View Gallery (optional)', 'omniverse' ),
	esc_html__( 'HTML Block categories', 'omniverse' ),
	esc_html__( 'HTML Block category', 'omniverse' ),
	esc_html__( 'Search categories', 'omniverse' ),
	esc_html__( 'Popular categories', 'omniverse' ),
	esc_html__( 'All categories', 'omniverse' ),
	esc_html__( 'Parent category', 'omniverse' ),
	esc_html__( 'Edit category', 'omniverse' ),
	esc_html__( 'Update category', 'omniverse' ),
	esc_html__( 'Add New category', 'omniverse' ),
	esc_html__( 'New category', 'omniverse' ),
	esc_html__( 'Add or remove categories', 'omniverse' ),
	esc_html__( 'Choose from most used', 'omniverse' ),
	esc_html__( 'Category', 'omniverse' ),
	esc_html__( 'Create/modify size guide table', 'omniverse' ),
	esc_html__( 'Choose product categories', 'omniverse' ),
);